services:
  vitorino-tt-rss:
    image: ghcr.io/tt-rss/tt-rss-web-nginx:sha-84554ba
    ports:
      - "8280:8280"
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    restart: unless-stopped
